stages:
  - validate
  - plan
  - apply
  - destroy
  - deploy

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    
before_script:
  - cd terraform
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - ls 
  - pwd 
  - rm -rf .terraform
  - terraform --version
  - terraform init

validate:
  stage: validate
  script:
  # - cd terraform
  - terraform validate
    
plan:
  stage: plan
  script:
    # - cd terraform
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - /builds/greengiant1/Nausicaas-Global-Green-Initiative/terraform/planfile
      
apply:
  stage: apply
  script:
    # - cd terraform
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  script:
    # - cd terraform
    - terraform destroy
  when: manual