AWSTemplateFormatVersion: 2010-09-09
##################################
#To ADD:
#VPC
#Subnet
#Security Groupe

######## Aurora RDS Configuration ###########
  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      Engine: aurora
      EngineMode: provisioned
      DBSubnetGroupName: !Ref DBSubnetGroup
      Tags:
        - Key: Environment
          Value: production
        - Key: Owner
          Value: GreenGiants
        - Key: Type
          Value: RDS-Cluster

  DBSubnetGroup: 
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties: 
      DBSubnetGroupDescription: SubnetGroup for new aurora cluster
      SubnetIds: 
       - !Ref PrivateSubnetA
       - !Ref PrivateSubnetB
